config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :experts, controllers: {
    # registrations: 'experts/registrations',
    sessions: 'experts/sessions',
  }
  devise_for :users, controllers: {
    # registrations: 'users/registrations',
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  scope "(:locale)", locale: /en|zh/ do
    resources :cars do
      collection do
        get   'models'
        get   'bodystyles'
        get   'styletrims'
        get   'fetch'
        get   'checklistdefinition'
        get   'car_detail'
	get   'car_love'
      end
      member do
        get   'checklist'
        post  'checklist'
        get   'craigslist'
      end
      resources :car_pictures
    end
    match '/search/cars', to: 'cars#index', via: 'post'
    match '/search/cars', to: 'cars#index', via: 'get'


    # Routes for handling the operation on user's cars
    resources :users do
      member do
        get :cars
        get :appointments
        get :sell_transactions
        get :buy_transactions
        get :appointment_list
      end
      collection do
        post :signin
        post :signup
      end
    end


    resources :charges do
      collection do
        post :charge
      end
    end

    resources :easy_transfers do
      member do
        post  :confirm
      end
    end

    # resources :experts do
    resources :experts, only: [:index, :show, :edit, :update] do
      member do
        get   :editAvailableTime
        post  :updateAvailableTime
        get   :scheduleAppointments
        post  :scheduleAppointments
        get   :reports
        get   :appointments
      end
    end

    resources :sell_requests do
      collection do
        post :new_user
        post :create_appointment
        get :get_all_price
        get :get_vininfo
        get :available_time_windows
      end
    end

    resources :appointments do
      collection do
        get :available_time_windows
      end
    end

    # Different root paths
    match '/faq', to: 'static_pages#faq', via: 'get'
    match '/terms_policy', to: 'static_pages#terms_policy', via: 'get'


    #car model
    resource :car_models do
      get 'models', on: :collection
      get 'years', on: :collection
      get 'stylenames', on: :collection
      get 'get_make', on: :collection
      get 'get_model', on: :collection
      get 'get_body', on: :collection
      get 'get_trim', on: :collection
      get 'get_drivetrain', on: :collection
      get 'get_transmission', on: :collection
    end

    resources :car_transactions
    resources :car_pictures

    match '/driver_license' => 'driver_license#index', via: 'get'
    match '/driver_license/game' => 'driver_license#game', via: 'get'
    match '/driver_license/test' => 'driver_license#test', via: 'get'
    match '/driver_license/practice' => 'driver_license#practice', via: 'get'
    match '/driver_license/newgame' => 'driver_license#newgame', via: 'get'
    match '/driver_license/:id' => 'driver_license#show', via: 'get'

  end

  #Api definition
  namespace :api, defaults: {format: :json} do
    scope module: :v1 , constraints: ApiConstraints.new(version: 1, default: true) do
      #Our resources here
      # get 'api_tokens', to: :index
      # get 'api_tokens/show', to: :show
      get 'expertapi/get_token' => 'expertapi#get_token'
      get 'expertapi/get_expert_info' => 'expertapi#get_expert_info'
      get 'expertapi/get_appointments' => 'expertapi#get_appointments'
      get 'expertapi/get_user_info' => 'expertapi#get_user_info'
      get 'expertapi/get_time_window' => 'expertapi#get_time_window'

    end
  end

  root 'static_pages#home'

  get '/:locale' => 'static_pages#home'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, :omniauth_providers => [:facebook]

  has_many :appointments
  has_many :sell_requests

  has_many :sell_transactions, foreign_key: "seller_id", class_name: "CarTransaction"
  has_many :buy_transactions, foreign_key: "buyer_id", class_name: "CarTransaction"

  has_many :cars, foreign_key: "owner_id", class_name: 'Car'
  has_many :easy_transfers, inverse_of: :user, dependent: :destroy

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      #user.image = auth.info.image # assuming the user model has an image
    end
  end

  def to_s
    "#{email}"
  end

end

app/controllers/user/cars_controller.rb
class User::CarsController < ApplicationController
  before_action :authenticate_user!

  # GET /user/:id/cars
  def index
    @cars = current_user.cars
    if current_user.id != params[:user_id].to_i
      redirect_to root_path
    end
    return @cars if @cars else []
  end

  # private
  #   def user_params
  #     params.require(:user).permit(:user_id)
  #   end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  #clear_respond_to
  respond_to :json
  before_filter :configure_sign_up_params, only: [:create]
  before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   @user = User.new
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  def edit
    if params[:id].to_s == current_user.id.to_s
      super
    else
      redirect_to root_url
    end
  end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:sign_up) << :phone
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.for(:account_update) << :name
    devise_parameter_sanitizer.for(:account_update) << :phone
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  #clear_respond_to
  respond_to :json
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in, only: :show
  # before_action :admin_user, only: :index
  skip_before_filter :verify_authenticity_token, only: [:signin, :signup]

  def show
    if current_user.admin?
      @user = User.find_by(id: params[:id])
    else
      @user = current_user
    end
  end

  def index
    redirect_to root_path
  end

  def edit
    if current_user.id != params[:id].to_i
      redirect_to root_path
    else
      @user = current_user
    end
  end

  def update
    if current_user.id != params[:id].to_i
      redirect_to root_path
    else
      current_user.name = params[:user][:name]
      current_user.email = params[:user][:email]
      current_user.phone = params[:user][:phone]
      current_user.save
      redirect_to current_user
    end
  end

  def cars
    check_same_user
    @cars = current_user.cars
    render 'show_cars'
  end

  def appointments
    check_same_user
    @appointments = current_user.appointments
    render 'show_appointments'
  end

  def appointment_list
    # check_same_user
    today = params[:today] ? Date.parse(params[:today]) : Date.today
    time_range = today.at_beginning_of_month...today.at_beginning_of_month.next_month
    user = User.find(params[:id])
    @appointments = user.appointments.joins(:time_window)
                        .where("time_windows.date" => time_range)
                        .select("appointments.*, time_windows.date as date, time_windows.hour as hour")

    # unscheduled appointments
    twids = []
    # outer join was used only to make date and hour available in json
    unscheduled = user.appointments.where(time_window_id: nil)
               .joins("LEFT OUTER JOIN time_windows ON appointments.time_window_id = time_windows.id")
               .select("appointments.*, time_windows.date as date, time_windows.hour as hour")
    unscheduled.each { |apt| twids |= apt.time_window_ids }
    time_windows = TimeWindow.where(id: twids).where(date: time_range)  # time windows in this month
    correct_twids = time_windows.map { |tw| tw.id }  # time_window_id that falls in this month
    tw_hash = {}
    time_windows.each do |tw| tw_hash[tw.id] = tw end
    unscheduled_thismonth = unscheduled.select { |apt| (apt.time_window_ids & correct_twids).size != 0 }
    duplicate_tws = []
    unscheduled_thismonth.each do |apt|
      (apt.time_window_ids & correct_twids).each do |twid|
        dup_apt = apt.dup
        dup_apt.id = apt.id  # duplicated ActiveRecord has no id
        dup_apt.date = tw_hash[twid].date
        dup_apt.hour = tw_hash[twid].hour
        duplicate_tws << dup_apt
      end
    end
    render json: @appointments + duplicate_tws
  end

  def sell_transactions
    check_same_user
    @transactions = current_user.sell_transactions
    @cars = current_user.cars
    render 'show_transactions', locals: { type: 0 }
  end

  def buy_transactions
    check_same_user
    user = current_user
    @transactions = user.sell_transactions
    render 'show_transactions', locals: { type: 1 }
  end

  def signin
    if request.post?
      user = authenticate(params[:email], params[:password])
      if not user
        render json: {message: "Signin failed!"}
        return
      end
      sign_in user
      if user_signed_in?
        render json: {message: "Signin success!", email: current_user.email}
      else
        render json: {message: "Signin failed!"}
      end
      return
    end
    render json: {message: "Invalid parameters!"}
  end

  def signup
    if params[:user][:password] != params[:user][:password_confirmation]
      render json: {message: "Passwords do not match!"}
      return
    end
    user = User.new(params.require(:user).permit(:name, :email, :phone))
    user.password = params[:user][:password]
    if user.save
      sign_in user
      render json: {message: "Signup success!"}
    else
      render json: user.errors
    end
  end

  def authenticate(email, password)
    user = User.find_by(:email => email)
    return nil unless user
    user.valid_password?(password) ? user : nil
  end

  private

  def check_same_user
    if current_user.id != params[:id].to_i
      redirect_to root_path
    end
  end

  def signed_in
    unless user_signed_in?
      redirect_to root_url
    end
  end

  def admin_user
    unless user_signed_in? || current_user.admin?
      redirect_to root_url
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def car_status_str(status)
    Car.car_status status
  end

  def appointment_type_str(appointment)
    if appointment.appointment_type == 0
      "sell"
    else
      "test-drive"
    end
  end

  def sell_transaction_status_str(status)
    if status == 0 or status == 1
      # Both sale-pending and processing-payment accounts for sale-pending for seller
      "sale-pending"
    else
      # Both delivering and delivered accounts for sold for seller
      "sold"
    end
  end

  def buy_transaction_status_str(status)
    if status == 0
      "processing-payment"
    elsif status == 1
      "sale-pending"
    elsif status == 2
      "delivering"
    else
      "delivered"
    end
  end
end

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xs-offset-0 col-sm-offset-0 col-md-offset-3 col-lg-offset-3 toppad" >

      <div class="panel panel-info">
        <div class="panel-heading">
          <%= content_tag "h3", current_user.name, class: "panel-title" %>
        </div>
        <div class="panel-body">
          <%= form_for(@user) do |f| %>
            <div class="row">
              <div class="col-md-3 col-lg-3" align="center">
                <img alt="User Pic" src="http://babyinfoforyou.com/wp-content/uploads/2014/10/avatar-300x300.png" class="img-circle img-responsive">
              </div>
              <div class=" col-md-9 col-lg-9 ">
                <table class="table table-user-information">
                  <tbody>
                  <tr>
                    <td>User Name:</td>
                    <td><%= f.text_field :name, class: "form-control" %></td>
                  </tr>
                  <tr>
                    <td>Email address:</td>
                    <td><%= f.text_field :email, class: "form-control" %></td>
                  </tr>
                  <tr>
                    <td>Phone Number</td>
                    <td><%= f.text_field :phone, class: "form-control" %></td>
                  </tr>
                  </tbody>
                </table>
              </div>
            </div>
            <div class="panel-footer">
              <%= f.submit "Update", class: "btn btn-sm btn-success" %>
              <span class="pull-right">
                <a type="button" class="btn btn-sm btn-danger">Cancel</a>
              </span>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <hr class="tall">
    </div>


    <div class="col-md-12"> <h4>My Profile</h4> </div>
    <table class="table">
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Phone</th>
        <th>Profile & Appointments</th>
      </tr>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td><%= user.phone %></td>
          <td><%= link_to "#{user.appointments.count} #{"Appointment".pluralize(user.appointments.count)}", user  %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/users/show_cars.html.erb
<div class="row checkbox-container">
  <span class="button-checkbox">
        <button id="inspected" type="button" class="btn" data-color="primary">Inspected</button>
        <input type="checkbox" class="hidden" />
  </span>
  <span class="button-checkbox">
      <button id="listing" type="button" class="btn" data-color="primary">Selling</button>
      <input type="checkbox" class="hidden" />
  </span>
  <span class="button-checkbox">
      <button id="sale-pending" type="button" class="btn" data-color="primary">Sale pending</button>
      <input type="checkbox" class="hidden" />
  </span>
  <span class="button-checkbox">
      <button id="sold" type="button" class="btn" data-color="primary">Sold</button>
      <input type="checkbox" class="hidden" />
  </span>
</div>
<div class="row car-portfolio-container">
  <ul class="portfolio-list sort-destination" data-sort-id="portfolio">
    <% @cars.each do |car| %>
      <%= render partial: "shared/car", locals: {car: car, status: car_status_str(car.status)} %>
    <% end %>
  </ul>
</div>

app/views/users/show_transactions.html.erb
<style>
    body{
        overflow:auto;
        background-color:#F9F9FB;
    }
    .home_page_footer{
        background-color:transparent;
    }
    header{
        background-color: rgb(74,144,226);
        min-width:1280px;
    }
    ul{
        list-style-type: none;
    }
    .nav_title, .nav_item > a > div{
        color:white;
    }
    .signInBtn{
        color:white;
    }
    .signUpBtn{
        color:rgb(74,144,226);
        background-color:white;
    }
    .signUpBtn > span > a {
        color: rgb(74,144,226);
    }
    .form_user_photo:hover img{
        content:url("<%= asset_path 'user_center/uploader_0.png' %>");
    }
    .car_clickable{
        width:100%;
        margin: 0px;
        padding: 0px;
        height: 300px;
        background-color: white;
        float: left;
        border-radius:15px;
    }
  .car_clickable_img{
    padding:17px;
    height: 180px;
  }
    .car_clickable_outline{
        min-width:100px;
        margin:0;
        margin-bottom:15px;
        padding-left:0;
    }
    .car_clickable_img_detail div:nth-child(2){
        font-size:15px;
    }
    .user_center_right_container{
        height:auto;
        min-height:710px;
    }
    .divider-line{
        margin-bottom:10px;
    }
</style>
<div class="col-xs-12" align="center">
    <div class="user_center_container">
        <div class="user_center_left_container">
            <div class='user_center_nav'>
                <a href="/">
                    <span>Home</span>
                </a>
                &nbsp;>&nbsp;
                <span>
                    User Center
                </span>
            </div>
            <div class="user_center_left_bar">
                <div class="user_center_left_bar_title">
                    User Center
                </div>
                <div class="divider-line" style="margin-left:-20px;">
                </div>
                <ul class="user_center_left_bar_list">
                    <% if type == 0 %> 
                        <a href="<%= buy_transactions_user_path current_user %>">
                            <li>
                                <img class="list_square list_square_0" src="<%= asset_path 'homepage/user_buy_icon.png' %>"/>
                                <span>
                                    My Purchasing
                                </span>
                            </li>
                        </a>
                        <li class="user_center_active">
                            <a href="<%= sell_transactions_user_path current_user %>">
                                <img class="list_square list_square_1" src="<%= asset_path 'homepage/user_sell_icon_1.png' %>"/>
                                <span>
                                    My Selling
                                </span>
                            </a>
                        </li>
                    <% else %>
                        <a href="<%= buy_transactions_user_path current_user %>">
                            <li class="user_center_active">
                                <img class="list_square list_square_0" src="<%= asset_path 'homepage/user_buy_icon_1.png' %>"/>
                                <span>
                                    My Purchasing
                                </span>
                            </li>
                        </a>
                        <a href="<%= sell_transactions_user_path current_user %>">
                            <li>
                                <img class="list_square list_square_1" src="<%= asset_path 'homepage/user_sell_icon.png' %>"/>
                                <span>
                                    My Selling
                                </span>
                            </li>
                         </a>
                    <% end %>
                    
                    <a href="<%= appointments_user_path current_user %>">
                        <li>
                            <img class="list_square list_square_2" src="<%= asset_path 'homepage/user_appointment_icon.png' %>"/>
                            <span>
                                My Appointment
                            </span>
                        </li>
                    </a>


                    <a href="<%= user_path current_user %>">
                        <li>
                            <img class="list_square list_square_3" src="<%= asset_path 'homepage/user_profile_icon.png' %>"/>
                            <span>
                                My Profile
                            </span>
                        </li>
                    </a>
                   
                    <li style="cursor:not-allowed">
                        <img class="list_square list_square_4" src="<%= asset_path 'homepage/user_wishlist_icon.png' %>"/>
                        <span>
                            My Wish List (Future)
                        </span>
                    </li>
                </ul>
            </div>
        </div>
        <div class="user_center_right_container">
            <% if type == 0 %>
                <div class="user_center_left_bar_title">
                    My Selling
                </div>
                <div class="divider-line" style="margin-left:-20px;">
                </div>
                <%= render partial: "shared/car", collection: @cars %>
            <% else %>
                <div class="user_center_left_bar_title">
                    My Purchasings
                </div>
                <div class="divider-line" style="margin-left:-20px;">
                </div>
                
            <% end %>
            
            <!-- my pusrchasing item -->
            
        </div>
    </div>
    <div class="col-xs-12 home_page_footer all-to-none">
          <div class="col-xs-12 all-to-none footer_upper">
              <div class="footer_upper_left all-to-none">
                 
              </div>
              <div class="footer_upper_middle all-to-none">
                  <a href="/faq">
                      <div class="col-xs-3 all-to-none" style="text-align:center;">
                          FAQ
                      </div>
                  </a>
                  <div class="col-xs-3 all-to-none" style="text-align:center;">
                      About Us
                  </div>
                  <a href="/terms_policy">
                      <div class="col-xs-3 all-to-none" style="text-align:center;">
                          Terms & Policy
                      </div>
                  </a>
                  <a href="mailto:tripalink.helpcenter@gmail.com">
                      <div class="col-xs-3 all-to-none" style="text-align:center;">
                          Contact Us
                      </div>
                  </a>
              </div>
              <div class="footer_upper_right all-to-none">
                  <div style="max-width: 190px;">
                     <a href="https://www.facebook.com/pages/Tripalink/1045740125437551">      
                         <div class="col-xs-3 foot_img_0">
                             <img src="<%= asset_path 'homepage/facebook.png' %>" width="40px" height="40px" />
                         </div>
                     </a>
                     <a href="https://twitter.com/tripalink">
                         <div class="col-xs-3 foot_img_1">
                             <img src="<%= asset_path 'homepage/twitter.png' %>" width="40px" height="40px" />
                         </div>
                     </a>
                     <div class="col-xs-3 foot_img_2" style="cursor:not-allowed">
                         <img src="<%= asset_path 'homepage/weibo.png' %>" width="40px" height="40px" />
                     </div>
                     <div class="col-xs-3 foot_img_3" style="cursor:not-allowed">
                         <img src="<%= asset_path 'homepage/wechat.png' %>" width="40px" height="40px" />
                     </div>
                  </div>
              </div>
              <div class="col-xs-12" align="center">
                  <div class='footer_lower'>
                      2015 Tripalink Corp. All Rights Reserved.
                  </div>
              </div>
           </div>
       </div>
</div>
<script>
  $(function() {
      $(window).scroll(function(){
          var scrollTop = $(window).scrollTop();
          if(scrollTop != 0) {
            $('header').css('background','rgba(74,144,226,0.8)');
            $('.nav_title, .nav_item > a > div, .signInBtn').css('color','white');  
            $('.signUpBtn').css('background-color','white');
            $('.signUpBtn, .signout a').css('color','rgba(74,144,226,1)');
          }
          else {
            $('header').css('background','rgba(74,144,226,0.8)');
            $('.nav_title, .nav_item > a > div, .signInBtn').css('color','white');  
            $('.signUpBtn').css('background-color','white');
            $('.signUpBtn, .signout a').css('color','rgba(74,144,226,1)');
          }
      });
  });
</script> 

<!--
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <hr class="tall">
    </div>

    <% if type == 0 %>
      <div class="col-md-12">
        <h4>sale transactions</h4>
      </div>
      <div class="row checkbox-container">
        <span class="button-checkbox">
          <button id="sale-pending" type="button" class="btn" data-color="primary">Sale pending</button>
            <input type="checkbox" class="hidden" />
        </span>
        <span class="button-checkbox">
          <button id="sold" type="button" class="btn" data-color="primary">Sold</button>
            <input type="checkbox" class="hidden" />
        </span>
      </div>
      <div class="row car-portfolio-container">
        <% @cars.each do |car| %>
          <ul class="portfolio-list sort-destination" data-sort-id="portfolio">
            <%= render partial: "shared/car",
                       locals: { car: car, status: sell_transaction_status_str(car.status) } %>
          </ul>
        <% end %>
      </div>
    <% else %>
    
      <div class="col-md-12">
        <h4>Purchase transactions</h4>
      </div>
      <div class="row checkbox-container">
        <span class="button-checkbox">
          <button id="processing-payment" type="button" class="btn" data-color="primary">Processing Payment</button>
            <input type="checkbox" class="hidden" />
        </span>
        <span class="button-checkbox">
          <button id="sale-pending" type="button" class="btn" data-color="primary">Sale Pending</button>
            <input type="checkbox" class="hidden" />
        </span>
        <span class="button-checkbox">
          <button id="delivering" type="button" class="btn" data-color="primary">Delivering</button>
            <input type="checkbox" class="hidden" />
        </span>
        <span class="button-checkbox">
          <button id="delivered" type="button" class="btn" data-color="primary">Delivered</button>
            <input type="checkbox" class="hidden" />
        </span>
      </div>
      <div class="row car-portfolio-container">
        <% @transactions.each do |transaction| %>
          <ul class="portfolio-list sort-destination" data-sort-id="portfolio">
            <%= render partial: "shared/car",
                       locals: { car: transaction.car, status: buy_transaction_status_str(transaction.status) } %>
          </ul>
        <% end %>
      </div>
    <% end %>
  </div>
</div>
-->