config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :experts, controllers: {
    # registrations: 'experts/registrations',
    sessions: 'experts/sessions',
  }
  devise_for :users, controllers: {
    # registrations: 'users/registrations',
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  scope "(:locale)", locale: /en|zh/ do
    resources :cars do
      collection do
        get   'models'
        get   'bodystyles'
        get   'styletrims'
        get   'fetch'
        get   'checklistdefinition'
        get   'car_detail'
	get   'car_love'
      end
      member do
        get   'checklist'
        post  'checklist'
        get   'craigslist'
      end
      resources :car_pictures
    end
    match '/search/cars', to: 'cars#index', via: 'post'
    match '/search/cars', to: 'cars#index', via: 'get'


    # Routes for handling the operation on user's cars
    resources :users do
      member do
        get :cars
        get :appointments
        get :sell_transactions
        get :buy_transactions
        get :appointment_list
      end
      collection do
        post :signin
        post :signup
      end
    end


    resources :charges do
      collection do
        post :charge
      end
    end

    resources :easy_transfers do
      member do
        post  :confirm
      end
    end

    # resources :experts do
    resources :experts, only: [:index, :show, :edit, :update] do
      member do
        get   :editAvailableTime
        post  :updateAvailableTime
        get   :scheduleAppointments
        post  :scheduleAppointments
        get   :reports
        get   :appointments
      end
    end

    resources :sell_requests do
      collection do
        post :new_user
        post :create_appointment
        get :get_all_price
        get :get_vininfo
        get :available_time_windows
      end
    end

    resources :appointments do
      collection do
        get :available_time_windows
      end
    end

    # Different root paths
    match '/faq', to: 'static_pages#faq', via: 'get'
    match '/terms_policy', to: 'static_pages#terms_policy', via: 'get'


    #car model
    resource :car_models do
      get 'models', on: :collection
      get 'years', on: :collection
      get 'stylenames', on: :collection
      get 'get_make', on: :collection
      get 'get_model', on: :collection
      get 'get_body', on: :collection
      get 'get_trim', on: :collection
      get 'get_drivetrain', on: :collection
      get 'get_transmission', on: :collection
    end

    resources :car_transactions
    resources :car_pictures

    match '/driver_license' => 'driver_license#index', via: 'get'
    match '/driver_license/game' => 'driver_license#game', via: 'get'
    match '/driver_license/test' => 'driver_license#test', via: 'get'
    match '/driver_license/practice' => 'driver_license#practice', via: 'get'
    match '/driver_license/newgame' => 'driver_license#newgame', via: 'get'
    match '/driver_license/:id' => 'driver_license#show', via: 'get'

  end

  #Api definition
  namespace :api, defaults: {format: :json} do
    scope module: :v1 , constraints: ApiConstraints.new(version: 1, default: true) do
      #Our resources here
      # get 'api_tokens', to: :index
      # get 'api_tokens/show', to: :show
      get 'expertapi/get_token' => 'expertapi#get_token'
      get 'expertapi/get_expert_info' => 'expertapi#get_expert_info'
      get 'expertapi/get_appointments' => 'expertapi#get_appointments'
      get 'expertapi/get_user_info' => 'expertapi#get_user_info'
      get 'expertapi/get_time_window' => 'expertapi#get_time_window'

    end
  end

  root 'static_pages#home'

  get '/:locale' => 'static_pages#home'

end

app/models/car.rb
class Car < ActiveRecord::Base
  DEFAULT_CHECKLIST = ["v1.0", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "0", "0", "0", "0", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "0", "0", "0", "0", "0", "0", "0", "0", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1"]

  before_create :fill_default_checklist

  belongs_to :car_model, inverse_of: :cars
  has_many :car_pictures, inverse_of: :car, dependent: :destroy
  has_many :appointments
  has_one :car_transaction
  belongs_to :expert, class_name: "Expert", foreign_key: "inspector_id"
  belongs_to :owner, class_name: "User", foreign_key: "owner_id"

  # The color references
  belongs_to :interior_color, :class_name => 'CarColor', :foreign_key => 'interior_color_id'
  belongs_to :exterior_color, :class_name => 'CarColor', :foreign_key => 'exterior_color_id'

  has_many :car_feature_relations, class_name: 'CarFeatureRelation', foreign_key: 'car_id', dependent: :destroy
  has_many :features, through: :car_feature_relations, source: :feature
  accepts_nested_attributes_for :features

  has_many :easy_transfers, inverse_of: :car, dependent: :destroy

  # Status keys
  STATUS_ALL_KEY = 0
  STATUS_PRE_INSPECTED_KEY = 1
  STATUS_INSPECTED_KEY = 2
  STATUS_LISTING_FOR_SALE_KEY = 3
  STATUS_SALE_PENDING_KEY = 4
  STATUS_SOLD_KEY = 5
  STATUS_DELETED_KEY = 6

  # Status value
  STATUS_ALL_VALUE = "all"
  STATUS_PRE_INSPECTED_VALUE = "pre-inspected"
  STATUS_INSPECTED_VALUE = "inspected"
  STATUS_LISTING_FOR_SALE_VALUE = "listing"
  STATUS_SALE_PENDING_VALUE = "sale-pending"
  STATUS_SOLD_VALUE = "sold"
  STATUS_DELETED_VALUE = "deleted"

  # Status map
  STATUS_MAP = {
      STATUS_ALL_KEY => STATUS_ALL_VALUE,
      STATUS_PRE_INSPECTED_KEY => STATUS_PRE_INSPECTED_VALUE,
      STATUS_INSPECTED_KEY => STATUS_INSPECTED_VALUE,
      STATUS_LISTING_FOR_SALE_KEY => STATUS_LISTING_FOR_SALE_VALUE,
      STATUS_SALE_PENDING_KEY => STATUS_SALE_PENDING_VALUE,
      STATUS_SOLD_KEY => STATUS_SOLD_VALUE,
      STATUS_DELETED_KEY => STATUS_DELETED_VALUE
  }

  def Car.car_status(status)
    return STATUS_MAP[status]
  end

  def location
    if city.blank? || state.blank?
      "#{city}#{state}"
    else
      "#{city}, #{state}"
    end
  end

  def mpg
    c, h = car_model.fuelEconomy.match(/(\d*)\/(\d*) mpg/).captures
    "#{c} City / #{h} Hwy"
  end

  def fill_default_checklist
    self.checklist = DEFAULT_CHECKLIST
  end

  def to_s
    "#{owner} #{car_model}"
  end
end

app/views/shared/_appointment_cancel_alert.html.erb
      <!-- Modal -->
      <div id="myModal" class="modal fade" role="dialog">
        <div class="modal-dialog">

          <!-- Modal content-->
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
              <h4 class="modal-title">Cancel an appointment</h4>
            </div>
            <div class="modal-body">
              <p>To cancel an appointment, please call our number or send an email to <a href="mailto:tripalink.dev@gmail.com">Administrator</a></p>
              
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
          </div>

        </div>
      </div>

app/views/shared/_car.html.erb
<% if not defined? status %>
  <% status = "undefined" %>
<% end %>
<%= content_tag "div",
                class: "col-md-4 col-sm-4 col-xs-12 car_clickable_outline",
                data: {status: status, carid: car.id} do %>
  <span class="product-thumb-info car_clickable">
    <% if car.status == 5 %>
      <% soldstring = car.soldinndays == -1 ? "Sold" : car.soldinndays == 0 ? "Sold instantly" : "Sold in #{car.soldinndays} #{"day".pluralize(car.soldinndays)}" %>
        <div class="ribbon-wrapper-green default">
            <div class="ribbon-green address_list_tag">
                <span><%= soldstring %></span>
            </div>
        </div>
    <% end %>
    <% if car.status == 4 %>
        <div class="ribbon-wrapper-green default">
            <div class="ribbon-green address_list_tag">
                <span>Sale pending</span>
            </div>
        </div>
    <% end %>
    <% if car.status != 5 && car.status != 4 %>  
        <a href="<%= car_path car %>">
    <% end  %>
      <div class="car_clickable_img">
        <% if !car.car_pictures.nil? and !car.car_pictures.first.nil? %>
          <div class="car_clickable_img-img" style="background-image:url(<%= car.thumbnail %>)">
<!--
              <div class='col-xs-12 car_clickable_img_price'>
                  $<%= number_with_delimiter(car.price) %>
              </div>
-->
          </div>
        <% else %>
          <div class="car_clickable_img-img" style="background-image:url(<%= 'img/products/product-1.jpg'%>)">
          </div>
        <% end %>
      </div>
      <div class="col-xs-12 car_clickable_img_detail">
        <div class="col-xs-12">
          <span class="col-xs-12 all-to-none">
            <%=car.car_model.year%> <%= car.car_model.make %>
          </span>
          <span class="col-xs-12 all-to-none">
            <%= car.car_model.model %> <%= car.car_model.trim %>
          </span>
        </div>
        <div class="col-xs-12">
          <%= number_with_delimiter(car.mileage) %> Miles | <%= car.car_model.body%>
        </div>
        <div class="col-xs-12 car_img_price">
            <div class="car_img_our_price">
                $<%= number_with_delimiter(car.price) %>
            </div>
            <div class="car_img_kbb_dealer_price">
                KBB Price <del>$<%= number_with_delimiter(car.price_kbb_max_retail) %></del>
            </div>
        </div>
      </div>
    
    <% if car.status != 5 && car.status != 4 %>  
       </a>
    <% end  %>
      
  </span>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-danger">
			The form contains <%= pluralize(object.errors.count, "error") %>.
		</div>
		<ul>
		<% object.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
		</ul>
	</div>
<% end %>

app/views/shared/_report.html.erb
<% unless reports.empty? %>
  <table class="table">
    <tr>
      <th>Date</th>
      <th>Time</th>
      <th>User</th>
      <th>Car</th>
    </tr>
    <% reports.each do |apt| %>
      <% car = apt.car %>
      <% model = car.car_model %>
      <tr>
        <td><%= "#{apt.time_window.date}, #{apt.time_window.date.strftime("%A")}" %></td>
        <td><a href="<%= sell_request_path(apt.sell_request) %>"><%= "#{apt.time_window.hour}:00".to_time.strftime("%l %P") %></a></td>
        <td><%= link_to apt.user.name, apt.user %></td>
        <td><%= link_to "#{model.year} #{model.make}, #{model.model}" , car_path(apt.car) %></td>
        <% if apt.car.status == 1 %>
          <td><%= link_to "Start report", edit_car_path(apt.car) %></td>
        <% elsif apt.car.status == 2 %>
          <td><%= link_to "Change report", edit_car_path(apt.car) %></td>
        <% end %>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/shared/_sign_in.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <hr class="tall">
    </div>

    <div class="row">
      <div class="col-sm-6 col-sm-offset-3">
        <div class="featured-box featured-box-primary align-left mt-xlg">
          <div class="box-content">

            <div class="row">
              <div class="col-md-6">
                <h4 class="heading-primary text-uppercase mb-md">Log In</h4>
              </div>
              <% if resource_name == :user %>
                <div class="col-md-6 align-right">
                  or <%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %>
                </div>
              <% end %>
            </div>

            <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
              <div class="row">
                <div class="form-group">
                  <div class="col-md-12">
                    <%= f.label :email %><br />
                    <%= f.email_field :email, autofocus: true, class: "form-control input-lg" %>
                  </div>
                </div>
              </div>

              <div class="row">
                <div class="form-group">
                  <div class="col-md-12">
                    <%= f.label :password %>
                    <%= link_to "Forget Password?", new_password_path(resource_name), class: "pull-right" %>
                    <br>
                    <%= f.password_field :password, autocomplete: "off", class: "form-control input-lg" %>
                  </div>
                </div>
              </div>

              <div class="row">
                <% if devise_mapping.rememberable? -%>
                  <div class="col-md-6">
                    <%= f.check_box :remember_me %>
                    <%= f.label :remember_me %>
                  </div>
                <% end -%>

                <div class="col-md-6 pull-right">
                  <%= f.submit "Log in", class: "btn btn-primary pull-right mb-xl" %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<%#= render "users/shared/links" %>

app/views/shared/_sign_up.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <hr class="tall">
    </div>
  </div>

  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <div class="featured-box featured-box-primary align-left mt-xlg" style="">
        <div class="box-content">

          <div class="row">
            <div class="col-md-6">
              <h4 class="heading-primary text-uppercase mb-md">Register An Account</h4>
            </div>
            <% if resource_name == :user %>
              <div class="col-md-6 align-right">
                or <%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %>
              </div>
            <% end %>
          </div>

          <%= form_for(resource, url: registration_path(resource)) do |f| %>
            <%= devise_error_messages! %>
            <div class="row">
              <div class="form-group">
                <div class="col-md-12">
                  <%= f.label :email %> <br>
                  <%= f.email_field :email, autofocus: true, class: "form-control input-lg" %>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="form-group">
                <div class="col-md-6">
                  <%= f.label :name %> <br>
                  <%= f.text_field :name, class: "form-control input-lg" %>
                </div>

                <div class="col-md-6">
                  <%= f.label :phone %> <br>
                  <%= f.text_field :phone, class: "form-control input-lg" %>
                </div>
              </div>
            </div>

            <div class="row">
              <div class="form-group">
                <div class="col-md-12">
                  <%= f.label :password %>
                  <% if @minimum_password_length %>
                    <em>(<%= @minimum_password_length %> characters minimum)</em>
                  <% end %>
                  <br>
                  <%= f.password_field :password, autocomplete: "off", class: "form-control input-lg" %>
                </div>
              </div>
            </div>

            <div class="row">
              <div class="form-group">
                <div class="col-md-12">
                  <%= f.label :password_confirmation %> <br>
                  <%= f.password_field :password_confirmation, autocomplete: "off", class: "form-control input-lg" %>
                </div>
              </div>
            </div>

            <div class="row">
              <%= f.submit "Sign up", class: "btn btn-primary mb-xl col-md-8 col-md-offset-2" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_time_window.html.erb
<% today = Date.today %>
<% time_range = today...(today+1.week) %>
<% time_windows = @time_windows %>
<% twids = @apt && @apt.time_window_ids ? @apt.time_window_ids : [] %>
<table>
  <tr>
    <% time_range.each do |date| %>
      <th class="col-xs-1"><%= date.strftime("%a %m/%d") %></th>
    <% end %>
  </tr>
  <% tw_idx = 0 %>
  <% (9..19).step(2) do |hour| %>
    <tr>
      <% time_range.each do |date| %>
        <td class='col-xs-1'>
          <% tw = time_windows[tw_idx]; tw_idx += 1 %>
          <% if tw.date != date || tw.hour != hour %>
            <div class="col-xs-12 btn time-window-btn btn-default" twid="<%= tw.id %>" disabled="disabled">error</div>
            <% next %>
          <% end %>
          <% if action_name == "scheduleAppointments" %>
              <% apt_list = @appointment_ids.has_key?(tw.id) ? @appointment_ids[tw.id].join(' ') : nil %>
              <% apt_attrs = apt_list ? "#{ apt_list }" : "" %>
              <% if tw.reserved? %>
                  <div class="col-xs-12 btn time-window-btn btn-success" twid="<%= tw.id %>" apt_ids="<%= apt_attrs %>" disabled="disabled">
              <% elsif tw.notavailable? %>
                  <div class="col-xs-12 btn time-window-btn btn-default" twid="<%= tw.id %>" disabled="disabled">
              <% else # if tw.available? == true %>
                  <div class="col-xs-12 btn time-window-btn btn-primary" twid="<%= tw.id %>" apt_ids="<%= apt_attrs %>">
              <% end %>
          <% elsif action_name == "editAvailableTime" %>
              <% if tw.notavailable? %>
                  <div class="col-xs-12 btn time-window-btn btn-primary" twid="<%= tw.id %>">
              <% elsif tw.reserved? %>
                  <div class="col-xs-12 btn time-window-btn btn-danger" twid="<%= tw.id %>" disabled="disabled">
              <% else %>
                  <div class="col-xs-12 btn time-window-btn btn-success" twid="<%= tw.id %>">
              <% end %>
          <% else %>
              <% if twids.include?(tw.id)  #appointed by current user %>
                  <div class="col-xs-12 btn time-window-btn btn-success" twid="<%= tw.id %>">
              <% elsif tw.available? %>
                  <div class="col-xs-12 btn time-window-btn btn-primary" twid="<%= tw.id %>">
              <% else %>
                  <div class="col-xs-12 btn time-window-btn btn-default" twid="<%= tw.id %>" disabled="disabled">
              <% end %>

          <% end %>
          <%= "#{hour}:00".to_time.strftime("%l %P") %>
            </div>
        </td>
      <% end %>
    </tr>
  <% end %>
</table>

app/views/shared/_time_window_script.html.erb
<script>
$(document).ready(function() {
  $('.time-window-btn').click(function (evt) {
    var vals = [];
    var twid = $(evt.target).attr('twid');
    var hash = {};
    hash[twid] = true;
    $('#time_window_ids input').each(function(index,element){
      if ($(element).val() != "" && !hash.hasOwnProperty($(element).val()))
        vals = vals.concat($(element).val());
        hash[$(element).val()] = true;
    });
    console.log(vals);
    if (!$(evt.target).hasClass('btn-success')) {
      vals = vals.concat($(evt.target).attr('twid'));
    }
    console.log(vals);
    $(evt.target).toggleClass('btn-primary').toggleClass('btn-success');
    var i = 0;
    while (vals.length - i > 3) {
      $('.time-window-btn[twid="' + vals[i++] + '"]').toggleClass('btn-primary').toggleClass('btn-success');
    }
    $('#time_window_ids input').each(function(index,element){
      if (i < vals.length) {
        $(element).val(vals[i++]);
      } else {
        $(element).val("");
      }
    });
  });

  //Set selected time windows in table with data from hidden inputs
  $('#time_window_ids input').each(function(index,element){
    var twid = $(element).val();
    if (twid != "") {
      //$('.time-window-btn[twid="' + twid + '"]').toggleClass('btn-primary').toggleClass('btn-success');
    }
  });

});
</script>

app/views/shared/_time_window_script_expert.html.erb
<script>
$(document).ready(function() {
  $('.time-window-btn').click(function (evt) {
    var vals = [];
    var twid = $(evt.target).attr('twid');
    $('#time_window_ids input').each(function(index,element){
      if ($(element).val() != "" && $(element).val() != twid)
        vals = vals.concat($(element).val());
    });
    if (!$(evt.target).hasClass('btn-success'))
      vals = vals.concat($(evt.target).attr('twid'));
    console.log(vals);
    $(evt.target).toggleClass('btn-primary').toggleClass('btn-success');
    var input_html = $('#time_window_ids input')[0];
    var i = 0;
    $('#time_window_ids input').each(function(index,element){
      if (i < vals.length) {
        $(element).val(vals[i++]);
      } else {
        $(element).val("");
      }
    });
    for ( ; i < vals.length; ++i) {
        $('#time_window_ids').append(
                $(input_html).clone().val(vals[i])
        );
    }
  });
});
</script>

app/views/shared/_time_window_script_schedule.html.erb
<script>

    var ready = function() {
        $(".highlighter").click(function (evt) {
            evt.preventDefault();
            var apt_id = $(evt.target).attr("data-appointment-id");
            $(".time-window-btn[apt_ids*=" + apt_id + "]").toggleClass("appointment_outline");
        });
        $(".accept_link").click(function (evt) {
            evt.preventDefault();
            var apt_id = $(evt.target).attr("data-appointment-id");
            var tw_id = $(evt.target).attr("data-time-window-id");
            $("#myModal #appointment_id").val(apt_id);
            $("#myModal #time_window_id").val(tw_id);
        });
    };
//    $(document).on("page:change", function() {
//      ready();
//    });
    $(window).ready(ready);
    $(document).on('page:load', ready);
    $(document).ready(function() {
        $('.time-window-btn').click(function (evt) {
            $.each($(evt.target).attr("apt_ids").split(" "),
                    function(index, obj) {
                        if (!isNaN(parseInt(obj))) {
                            $("table.table tr[apt_id=" + obj + "]").toggleClass("appointment_outline");
                        }
                    }
            );
        });
    });
</script>