config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :experts, controllers: {
    # registrations: 'experts/registrations',
    sessions: 'experts/sessions',
  }
  devise_for :users, controllers: {
    # registrations: 'users/registrations',
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  scope "(:locale)", locale: /en|zh/ do
    resources :cars do
      collection do
        get   'models'
        get   'bodystyles'
        get   'styletrims'
        get   'fetch'
        get   'checklistdefinition'
        get   'car_detail'
	get   'car_love'
      end
      member do
        get   'checklist'
        post  'checklist'
        get   'craigslist'
      end
      resources :car_pictures
    end
    match '/search/cars', to: 'cars#index', via: 'post'
    match '/search/cars', to: 'cars#index', via: 'get'


    # Routes for handling the operation on user's cars
    resources :users do
      member do
        get :cars
        get :appointments
        get :sell_transactions
        get :buy_transactions
        get :appointment_list
      end
      collection do
        post :signin
        post :signup
      end
    end


    resources :charges do
      collection do
        post :charge
      end
    end

    resources :easy_transfers do
      member do
        post  :confirm
      end
    end

    # resources :experts do
    resources :experts, only: [:index, :show, :edit, :update] do
      member do
        get   :editAvailableTime
        post  :updateAvailableTime
        get   :scheduleAppointments
        post  :scheduleAppointments
        get   :reports
        get   :appointments
      end
    end

    resources :sell_requests do
      collection do
        post :new_user
        post :create_appointment
        get :get_all_price
        get :get_vininfo
        get :available_time_windows
      end
    end

    resources :appointments do
      collection do
        get :available_time_windows
      end
    end

    # Different root paths
    match '/faq', to: 'static_pages#faq', via: 'get'
    match '/terms_policy', to: 'static_pages#terms_policy', via: 'get'


    #car model
    resource :car_models do
      get 'models', on: :collection
      get 'years', on: :collection
      get 'stylenames', on: :collection
      get 'get_make', on: :collection
      get 'get_model', on: :collection
      get 'get_body', on: :collection
      get 'get_trim', on: :collection
      get 'get_drivetrain', on: :collection
      get 'get_transmission', on: :collection
    end

    resources :car_transactions
    resources :car_pictures

    match '/driver_license' => 'driver_license#index', via: 'get'
    match '/driver_license/game' => 'driver_license#game', via: 'get'
    match '/driver_license/test' => 'driver_license#test', via: 'get'
    match '/driver_license/practice' => 'driver_license#practice', via: 'get'
    match '/driver_license/newgame' => 'driver_license#newgame', via: 'get'
    match '/driver_license/:id' => 'driver_license#show', via: 'get'

  end

  #Api definition
  namespace :api, defaults: {format: :json} do
    scope module: :v1 , constraints: ApiConstraints.new(version: 1, default: true) do
      #Our resources here
      # get 'api_tokens', to: :index
      # get 'api_tokens/show', to: :show
      get 'expertapi/get_token' => 'expertapi#get_token'
      get 'expertapi/get_expert_info' => 'expertapi#get_expert_info'
      get 'expertapi/get_appointments' => 'expertapi#get_appointments'
      get 'expertapi/get_user_info' => 'expertapi#get_user_info'
      get 'expertapi/get_time_window' => 'expertapi#get_time_window'

    end
  end

  root 'static_pages#home'

  get '/:locale' => 'static_pages#home'

end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]
  skip_before_filter :verify_authenticity_token, only: [:checklist]

  # GET /cars
  # GET /cars.json
  def index
    params[:search] ||= {}
    params[:search].each { |key, value|
      # parse_attribute(key, value)
      if !value.nil? && value.is_a?(String)
        #value.gsub!(/[Mm][Ii][Nn]/, '0')
        #value.gsub!(/[Mm][Aa][Xx]/, '999999')
      end
    }
    params["search"].delete_if {|key, value|
      if (key == "car_model.make" || key == "car_model.model")
        false
      else
        (value.size == 3 && (value =~ /[Mm][Ii][Nn]/ || value =~ /[Mm][Aa][Xx]/)) ? true : false
      end
    }
    #params["search"] = params["search"].merge("status" => [3, 4, 5])
    params["search"] = params["search"].merge("status" => [3])
    @search = Search.new(Car, params[:search])
    @cars = @search.run(params[:page])
                .where(sold: false).order("status, created_at DESC")
                .includes(:car_model, :car_pictures)
    # debugger
    # @models = CarModel.pluck('DISTINCT make, model')
    respond_to do |format|
      format.html { render 'index' }
      format.json { render json: @cars }
    end
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
    if @car.checklist and @car.checklist.size > 0
      @checklistdefinition = getChecklistDefinition(@car.checklist[0])
    else
      @checklistdefinition = nil
    end
    print 'hello'
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
    @car = Car.find(params[:id])
    @checklistdefinition = getChecklistDefinition()
    @default_values = get_checkitem_default_values(@checklistdefinition)
    @check_item_index = get_check_item_index(@checklistdefinition)
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    # Update basic params
    @car.update_attributes(car_basic_params)
    # Update car's color
    color_params = car_color_params
    color_params.each do |color_type, color_name|
      color = CarColor.find_by_name(color_name)
      if color_type == "interior_color"
        @car.interior_color = color
      else
        @car.exterior_color = color
      end
    end

    # Update car's features
    feature_params = car_feature_params
    features = []
    feature_params.each do |feature_name, feature_selected|
      if feature_selected == "1"
        feature = CarFeature.find_by_name(feature_name)
        features << feature
      end
    end
    @car.features = features

    # Update car's checklists
    @check_item_index = get_check_item_index(getChecklistDefinition())
    checklist_params = car_checklist_params
    new_checklist = []
    checklist_params.each do |item_name, item_val|
      new_checklist[@check_item_index[item_name]] = item_val
    end
    @car.checklist = new_checklist
    # Update the status of car
    @car.status = 2

    @car.save
    redirect_to edit_car_path(@car)
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  #GET /cars/models?make=Porsche
  def models
    @car_models = CarModel.where(make: params[:make]).order(:model).pluck("DISTINCT model")
    # debugger
  end

  #GET /cars/bodystyles?make=Porsche&model=
  def bodystyles
    where_condition = {}
    where_condition[:make] = params[:make] if !params[:make].blank?
    where_condition[:model] = params[:model] if !params[:model].blank?
    @bodystyles = CarModel.where(where_condition).joins(:cars).pluck("DISTINCT body").sort
  end

  #GET /cars/styletrims?styleIds=101355672,101355906,101355720,101355908
  def styletrims
    styleIds = params[:styleIds].split(',')
    legitIds = styleIds.select{ |i| i.to_i != 0 }.map{ |i| i.to_i }
    @trims = CarModel.where(styleId: legitIds).map{ |v| v.trim }
  end

  #GET /cars/car_detail?id=?
  def car_detail
    c = Car.find(params[:id])
    render :json => c.detail
  end

  #GET /cars/love?id=?
  def car_love
    c = Car.find(params[:id])
    render :json => {love: c.love}
  end

  #
  def fetch
    plate = params["plate"]
    state = params["state"]
    fetcher = CarsHelper::VINFetcher.new
    vin = fetcher.fetchVINWithPlate(params[:plate], params[:state])
    if !vin || vin == ""
      return @styleId = "Failed to get VIN."
    end
    puts vin
    styleId = fetcher.fetchModelIdWithVIN(vin)
    puts styleId
    # debugger
    @car_model = CarModel.find_by(styleId: styleId)
    @styleId = styleId
  end

  def checklistdefinition
    ver = params[:version] || "latest"
    @checklist = getChecklistDefinition(ver)
    render json: @checklist
  end

  def checklist
    @car = Car.find(params[:id])
    if request.get?
      @checklist = @car.checklist
      render json: @checklist
    elsif request.post?
      json = params[:_json]
      if json.nil? or json.class != Array or json.size < 1 or getChecklistDefinition(json[0]) == nil
        respond_to do |format|
          format.json { render json: {message: "format error"}, status: :unprocessable_entity }
        end
        return
      end
      checklist = getFlatChecklistDefinition(json[0])
      if checklist.size + 1 != json.size
        respond_to do |format|
          format.json { render json: {message: "array size error"}, status: :unprocessable_entity }
        end
        return
      end
      @car.checklist = json
      respond_to do |format|
        if @car.save
          format.html { redirect_to cars_url(params[:id]), notice: 'The checklist of the car was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { redirect_to cars_url(params[:id]), notice: 'Fail to update the checklist of the car.' }
          format.json { render json: {message: "format error"}, status: :unprocessable_entity }
        end
      end
    end
  end

  def craigslist
    cl = CraigslistBot.new(Car.find(params[:id]))
    if cl.main
      render json: {message: 'You are only one step to successfully posting to Craigslist. Please checkout your email and click the link.'}
    else
      render json: {message: 'Failed in posting to Craigslist.'}
    end
  end

  def dealmoon
    c = DealmoonBot.new(Car.find(1))
    c.get_posting_page
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params[:car]
    end

    def car_basic_params
      params.require(:car).permit(:mileage)
    end

    def car_color_params
      params.require(:car).permit(:interior_color, :exterior_color)
    end

    def car_feature_params
      params.require(:feature).permit!
    end

    def car_checklist_params
      params.require(:checklist).permit!
    end

    # def car_basic_info_params
    #   params.require(:car).permit(:mileage)
    # end


    def getChecklistDefinition(version = "latest")
      if version == "latest" or version.nil?
        version = CONFIG_CHECKLIST["latest"]
      end
      CONFIG_CHECKLIST[version]
    end
    helper_method :getChecklistDefinition

    def getFlatChecklistDefinition(version= "latest")
      getChecklistDefinition(version).map{ |section|
        section["values"].each { |s|
          s["section"] = section["section"]
        }
        section["values"]
      }.flatten
    end

    def get_check_item_index(checklist_definition)
      check_item_index = {}
      idx = 0
      checklist_definition.each do |section|
        section["values"].each do |item|
          check_item_index[item["name"]] = idx
          idx += 1
        end
      end
      check_item_index
    end

    def get_checkitem_default_values(checklist_definition)
      default_values = []
      checklist_definition.each do |section|
        section["values"].each do |item|
          if item["type"] == "boolean"
            default_values << "1"
          else
            default_values << "0"
          end
        end
      end
    end
end

app/controllers/user/cars_controller.rb
class User::CarsController < ApplicationController
  before_action :authenticate_user!

  # GET /user/:id/cars
  def index
    @cars = current_user.cars
    if current_user.id != params[:user_id].to_i
      redirect_to root_path
    end
    return @cars if @cars else []
  end

  # private
  #   def user_params
  #     params.require(:user).permit(:user_id)
  #   end
end

app/helpers/cars_helper.rb
require 'cgi'
require 'rest_client'
require 'open-uri'
require 'nokogiri'

module CarsHelper
  class VINFetcher
    def initialize
      @email = "397703407@QQ.COM"
      @password = "397703407qq"
      plate = "6RBU987"  #params["plate"]
      state = "CA"  #params["state"]
      timestamp = "1434419840000"
      #@signature = "9548b3095b1219e641cad76c1c579247282c7d52b650c06ac574a7df09b56661e57a4eb5dcd2f6c1b3c6e65e0616a90fb58fae3a4e57d7a661407252384747be"
      @signature = ENV["carfax_signature"]
    end

    def fetchVINWithPlate(plate = "6RBU987", state="CA")
      # debugger
      (1..3).each { |trialno|
        if @signature == nil
          login
        end
        timestamp = (Time.now.getutc.to_i*1000).to_s
        url = "https://secured.carfax.com/traveler-api/quickvin/lookup.json?email=%s&timestamp=%s&signature=%s&plate=%s&state=%s" % [CGI.escape(@email), timestamp, @signature, CGI.escape(plate), CGI.escape(state)]
        puts '='*20 + "Trial NO. %s" % trialno.to_s
        puts url
        puts eval(ENV["carfax_cookies"])
        j = nil
        headers = {"Referer" => "https://secured.carfax.com/showroom/main.cfx",
          "User-Agent" => "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:38.0) Gecko/20100101 Firefox/38.0",
          :cookies => eval(ENV["carfax_cookies"])
        }
        begin
          j = JSON.parse(RestClient.get(url, headers))
          if j && j["quickVinResults"] && j["quickVinResults"][0] && j["quickVinResults"][0]["vin"]
            return j["quickVinResults"][0]["vin"]
          end
        rescue => err
          puts '='*20 + "Failed trial No. %s" % trialno.to_s
          puts err.message
          #puts err.backtrace
          login
        end
      }
      nil
    end

    def fetchModelIdWithVIN(vin="WBAKG7C51DJ437538")
      url = 'https://api.edmunds.com/v1/api/toolsrepository/vindecoder?vin=%s&fmt=json&api_key=v7nh772a4fe88gm3atabxnp4' % vin
      j = nil
      begin
        j = JSON.parse(open(url).read)
      rescue => err
        puts err.message
        puts err.backtrace
      end

      styleId = j['styleHolder'][0]['id']
    end

    def login
      url = "https://secured.carfax.com/showroom/login.cfx"
      params = '{"username":"%s","password":"%s"}' % [@email, @password]
      r = RestClient.post url, params, :content_type => 'application/json'
      url = "https://secured.carfax.com/showroom/main.cfx"
      token = nil
      begin
        token = JSON.parse(r)
      rescue => err
      end
      cookies = r.cookies.dup
      cookies["CFX_TOKEN"] = token["cfx_token"]
      html = RestClient.get(url,
        {:cookies => cookies})
      html.cookies.each do |key, value|
        cookies[key] = value
      end
      noko = Nokogiri::HTML(html)
      sig = noko.xpath '//div[@id="RunBox"]//form[@id="runByPlateStateForm"]/input[@id="signatureInput"]'
      if sig == nil || sig.size < 1
        puts "Could not find input signatureInput in runByPlateStateForm."
        return nil
      end
      ENV["carfax_signature"] = @signature = sig[0].attribute('value').value
      ENV["carfax_cookies"] = cookies.inspect
    end

  end


end

app/views/cars/_car_image_uploader.html.erb
<li class="col-md-6 clearfix">
  <div class="thumbnail clearfix">
    <h4><%= picture_type %></h4>
    <img src="http://placehold.it/320x200" alt="ALT NAME" class="pull-left clearfix" style='margin-right:10px'>
    <span>
    <%= fields_for(:car_picture, html: { multipart: true }) do |upload_form|  %>
      <%= upload_form.file_field picture_type %>
    <% end %>
      </span>
  </div>
</li>

app/views/cars/_color_picker.html.erb
<div class="tab-pane <%= color_type == "interior_color" ? "active" : "" %>" id=<%= color_type %>>
  <div class="panel-body">
    <% CarColor.all.each do |color| %>
      <div class="col-md-4">
        <%= content_tag :div, class: "well well-sm color-picker-chip", style: "border-right-color: #{color.value}" do %>
          <div class="radio">
            <label>
              <%= form.radio_button color_type.to_sym,
                                    color.name, checked: ((not car_color.nil?) and car_color.name == color.name) %>
              <%= color.name %>
            </label>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/cars/_dynamic_js.html.erb
<script type='text/javascript'>

function replaceOptions($select, data) {
  $.each(data, function(index, option) {
    $select.append(
      $("<option></option>")
        .attr('value', option)
        .text(option));
  });
}

function makeSelected() {
  var make = $('#search_car_model\\.make').val();
  $.get("/cars/models?make=" + make, function(data) {
    $('#search_car_model\\.model option:gt(0)').remove();
    replaceOptions($("#search_car_model\\.model"), data);
  });
  $.get("/cars/bodystyles?make=" + make, function(data) {
      $('#search_car_model\\.body option:gt(0)').remove();
      replaceOptions($("#search_car_model\\.body"), data);
  });
}

//makeSelected();
$('#search_car_model\\.make').bind("change",makeSelected);

$('#search_car_model\\.model').bind("change",function () {
  var make = $('#search_car_model\\.make').val();
  var model = $('#search_car_model\\.model').val();
  $.get("/cars/bodystyles?make=" + make + "&model=" + model, function(data) {
    $('#search_car_model\\.body option:gt(0)').remove();
    replaceOptions($("#search_car_model\\.body"), data);
  })
});
</script>

app/views/cars/_edit_basic_info.html.erb
<div class="timeline-badge"><i class="fa fa-info"></i></div>
<div class="timeline-panel">
  <i class="glyphicon glyphicon-chevron-down timeline-panel-btn"></i>
  <div class="timeline-heading">
    <h4 class="timeline-title">Basic information</h4>
  </div>
  <div class="timeline-body">
    <div class="col-lg-6">
      <div class="form-group">
        <%= form.label :mileage %>
        <div class="input-group">
          <%= form.text_field :mileage, class: "form-control" %>
          <span class="input-group-addon"><i class="glyphicon glyphicon-ok "></i></span>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/cars/_edit_car_checklist.html.erb
<div class="timeline-badge success"><i class="fa fa-bars"></i></div>
<div class="timeline-panel">
  <i class="glyphicon glyphicon-chevron-down timeline-panel-btn"></i>
  <div class="timeline-heading">
    <h4 class="timeline-title">Inspection Checklist</h4>
  </div>
  <div class="timeline-body">
    <div class="tabbable-panel">
      <div class="tabbable-line">
        <% max_num_tabs = 6 %>
        <ul class="nav nav-tabs ">
          <% @checklistdefinition.map{ |section| section["section"] }.each_with_index do |val, idx| %>
            <% if idx < max_num_tabs %>
              <li><%= link_to val, "#tabs-#{idx + 1}", data: { toggle: "tab" }, class: "tab" %></li>
            <% end %>
          <% end %>
        </ul>
        <ul class="nav nav-tabs ">
          <% @checklistdefinition.map{ |section| section["section"] }.each_with_index do |val, idx| %>
            <% if idx >= max_num_tabs %>
              <li><%= link_to val, "#tabs-#{idx + 1}", data: { toggle: "tab" }, class: "tab" %></li>
            <% end %>
          <% end %>
        </ul>
        <div class="tab-content">
          <% @checklistdefinition.each_with_index do |section, section_id| %>
            <%= render partial: 'checklist_picker', locals: { section_id: section_id, section: section } %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/cars/_edit_car_colors.html.erb
<div class="timeline-badge danger"><i class="fa fa-paint-brush"></i></div>
<div class="timeline-panel">
  <i class="glyphicon glyphicon-chevron-down timeline-panel-btn"></i>
  <div class="timeline-heading">
    <h4 class="timeline-title">Car Colors</h4>
  </div>
  <div class="timeline-body">
    <div class="tabbable-panel">
      <div class="tabbable-line">
        <ul class="nav nav-tabs ">
          <li class="active">
            <a href="#interior_color" data-toggle="tab">Interior</a>
          </li>
          <li>
            <a href="#exterior_color" data-toggle="tab">Exterior</a>
          </li>
        </ul>
        <div class="tab-content">
          <%= render partial: 'color_picker',
                     locals: { car_color: @car.interior_color, color_type: "interior_color", form: form }%>
          <%= render partial: 'color_picker',
                     locals: { car_color: @car.exterior_color, color_type: "exterior_color", form: form }%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/cars/_upload_car_images.html.erb
<div class="timeline-badge success"><i class="glyphicon glyphicon-credit-card"></i></div>
<div class="timeline-panel">
  <i class="glyphicon glyphicon-chevron-down timeline-panel-btn"></i>
  <div class="timeline-heading">
    <h4 class="timeline-title">Photos upload</h4>
  </div>
  <div class="timeline-body">
    <div class="tabbable-panel">
      <div class="tabbable-line">
        <div class="row">
          <div class="col-md-12">
            <ul class="thumbnails">
              <% picture_types = CarPicture.get_picture_types %>
              <% for i in 0..picture_types.count - 1 %>
                <%= render partial: 'car_image_uploader', locals: { index: i, picture_type: picture_types[i] } %>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/cars/bodystyles.json.erb
[<%= raw @bodystyles.map { |body| %{"#{body}"} }.join(',') %>]

app/views/cars/edit.html.erb
<div class="container">
  <% m = @car.car_model %>
  <h1><%= m.year %> <%= m.make %> <%= m.model %></h1>
  <div class="row">
    <%= form_for(@car) do |f| %>
    <ul class="timeline">
      <li>
        <!-- the section about car's basic information -->
        <%= render partial: 'edit_basic_info', locals: { form: f } %>
      </li>
      <li>
        <!-- the section about car's colors -->
        <%= render partial: 'edit_car_colors', locals: { form: f } %>
      </li>
      <li>
        <!-- the section about car's features -->
        <%= render partial: 'edit_car_features', locals: { form: f } %>
      </li>
      <li>
        <!-- the section about car's checklist -->
        <%= render partial: 'edit_car_checklist', locals: { form: f } %>
      </li>
    </ul>
  </div>
  <div class="row report-action-btns">
    <div class="col-md-offset-2 col-md-2">
      <%= link_to "Upload car picture", car_car_pictures_path(@car), class: "btn btn-info btn-block btn-outline" %>
    </div>
    <div class="col-md-offset-1 col-md-2">
      <%= f.submit "submit", class: "btn btn-success btn-block btn-outline " %>
    </div>
    <div class="col-md-offset-1 col-md-2">
      <%= link_to "Cancel", :back, class: "btn btn-danger btn-block btn-outline" %>
    </div>
  </div>
  <% end %>
</div>

app/views/cars/fetch.json.erb
<%= @styleId %>

app/views/cars/models.json.erb
[<%= raw @car_models.map { |m| %{"#{m}"} }.join(',') %>]

app/views/cars/new.html.erb
<h1>New Car</h1>

<%= render 'form' %>

<%= link_to 'Back', cars_path %>

app/views/cars/styletrims.json.erb
[<%= raw @trims.map { |trim| %{"#{trim}"} }.join(',') %>]