config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :experts, controllers: {
    # registrations: 'experts/registrations',
    sessions: 'experts/sessions',
  }
  devise_for :users, controllers: {
    # registrations: 'users/registrations',
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  scope "(:locale)", locale: /en|zh/ do
    resources :cars do
      collection do
        get   'models'
        get   'bodystyles'
        get   'styletrims'
        get   'fetch'
        get   'checklistdefinition'
        get   'car_detail'
	get   'car_love'
      end
      member do
        get   'checklist'
        post  'checklist'
        get   'craigslist'
      end
      resources :car_pictures
    end
    match '/search/cars', to: 'cars#index', via: 'post'
    match '/search/cars', to: 'cars#index', via: 'get'


    # Routes for handling the operation on user's cars
    resources :users do
      member do
        get :cars
        get :appointments
        get :sell_transactions
        get :buy_transactions
        get :appointment_list
      end
      collection do
        post :signin
        post :signup
      end
    end


    resources :charges do
      collection do
        post :charge
      end
    end

    resources :easy_transfers do
      member do
        post  :confirm
      end
    end

    # resources :experts do
    resources :experts, only: [:index, :show, :edit, :update] do
      member do
        get   :editAvailableTime
        post  :updateAvailableTime
        get   :scheduleAppointments
        post  :scheduleAppointments
        get   :reports
        get   :appointments
      end
    end

    resources :sell_requests do
      collection do
        post :new_user
        post :create_appointment
        get :get_all_price
        get :get_vininfo
        get :available_time_windows
      end
    end

    resources :appointments do
      collection do
        get :available_time_windows
      end
    end

    # Different root paths
    match '/faq', to: 'static_pages#faq', via: 'get'
    match '/terms_policy', to: 'static_pages#terms_policy', via: 'get'


    #car model
    resource :car_models do
      get 'models', on: :collection
      get 'years', on: :collection
      get 'stylenames', on: :collection
      get 'get_make', on: :collection
      get 'get_model', on: :collection
      get 'get_body', on: :collection
      get 'get_trim', on: :collection
      get 'get_drivetrain', on: :collection
      get 'get_transmission', on: :collection
    end

    resources :car_transactions
    resources :car_pictures

    match '/driver_license' => 'driver_license#index', via: 'get'
    match '/driver_license/game' => 'driver_license#game', via: 'get'
    match '/driver_license/test' => 'driver_license#test', via: 'get'
    match '/driver_license/practice' => 'driver_license#practice', via: 'get'
    match '/driver_license/newgame' => 'driver_license#newgame', via: 'get'
    match '/driver_license/:id' => 'driver_license#show', via: 'get'

  end

  #Api definition
  namespace :api, defaults: {format: :json} do
    scope module: :v1 , constraints: ApiConstraints.new(version: 1, default: true) do
      #Our resources here
      # get 'api_tokens', to: :index
      # get 'api_tokens/show', to: :show
      get 'expertapi/get_token' => 'expertapi#get_token'
      get 'expertapi/get_expert_info' => 'expertapi#get_expert_info'
      get 'expertapi/get_appointments' => 'expertapi#get_appointments'
      get 'expertapi/get_user_info' => 'expertapi#get_user_info'
      get 'expertapi/get_time_window' => 'expertapi#get_time_window'

    end
  end

  root 'static_pages#home'

  get '/:locale' => 'static_pages#home'

end

app/models/expert.rb
class Expert < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  #geokit-rails requirement
  acts_as_mappable

  has_many :appointments
  has_many :sell_requests

  mount_uploader :avatar, AvatarUploader
end

app/controllers/experts/confirmations_controller.rb
class Experts::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/experts/omniauth_callbacks_controller.rb
class Experts::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/experts/passwords_controller.rb
class Experts::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/experts/registrations_controller.rb
class Experts::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   @expert = Expert.new
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  #   def after_sign_up_path_for(resource)
  #     '/experts/sign_in'
  #   end

  # The path used after sign up for inactive accounts.
  #   def after_inactive_sign_up_path_for(resource)
  #     '/experts/sign_in'
  #   end

    # def after_sign_out_path_for(resource)
    #   byebug
    #   '/experts/sign_in'
    # end
end

app/controllers/experts/sessions_controller.rb
class Experts::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  protected
    def after_sign_out_path_for(resource)
      '/experts/sign_in'
    end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/experts/unlocks_controller.rb
class Experts::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/experts_controller.rb
class ExpertsController < ApplicationController
  before_action :authenticate_expert!

  def show
    check_same_expert
    @expert = Expert.find(params[:id])
  end

  def edit
    check_same_expert
    @expert = Expert.find(params[:id])
  end

  def update
    if current_expert.id != params[:id].to_i
      redirect_to '/experts'
    else
      current_expert.update_attributes(expert_update_params)
      redirect_to current_expert
    end
  end

  def appointments
    check_same_expert
    appontments_by_type =
        current_expert.appointments.where(appointment_type: params[:type])
    @appointments = appontments_by_type.paginate(page: params[:page])
    @appointment_type_str = Appointment.apt_type params[:type]

    respond_to do |format|
      format.html
      format.js
    end
  end

  def reports
    check_same_expert
    report_type = params[:type].to_i
    @reports = []
    current_expert.appointments.each do |appt|
      if appt.car.status == report_type
        @reports << appt
      end
    end
    respond_to do |format|
      format.html
      format.js
    end
  end

  def editAvailableTime
    @expert = Expert.find(params[:id])
    generateTimeWindows
  end

  def updateAvailableTime
    check_same_expert
    expert = Expert.find_by(id: params[:id])
    workingtws = TimeWindow.where(expert_id:expert.id)
                     .where.not(status:0)
                     .where(date: Date.today..(Date.today+1.week))

    paramids = params[:time_window_ids].select{ |i| i.to_s != 0 }.map{ |i| i.to_i }
    twids = workingtws.map{ |tw| tw.id }
    # newtws = paramids - twids
    offtws = twids - paramids
    TimeWindow.where(expert_id: expert.id).where(status: TimeWindow.statuses[:notavailable]).where(id: paramids)
        .update_all(status: TimeWindow.statuses[:available])
    TimeWindow.where(expert_id: expert.id).where.not(status: TimeWindow.statuses[:reserved]).where(id: offtws)
        .update_all(status: TimeWindow.statuses[:notavailable])
    redirect_to editAvailableTime_expert_path
  end

  def scheduleAppointments
    check_same_expert
    if request.get?
      @expert = Expert.find(params[:id])
      @working_time_windows = TimeWindow.where(expert_id:@expert.id)
                                  .where.not(status:0)
                                  .where(date: Date.today..(Date.today+1.week))
      twids = @working_time_windows.map{ |t| t.id }
      @appointments = Appointment.where(expert_id:@expert.id).order(:id)
                          .where("time_window_ids && ARRAY[?]", twids)
      @appointment_ids = Hash.new { |h, k| h[k] = [] }
      @appointments.each do |apt|
        apt.time_window_ids.each do |time_window_id|
          @appointment_ids[time_window_id] << apt.id
        end
      end
      generateTimeWindows
      # @working_time_windows.each do |time_window|
      #   time_window.appointment_ids = h.has_key?(time_window.id) ? h[time_window.id] : "";
      # end
    elsif request.post?
      apt = Appointment.find(params[:appointment_id])
      time_window_id = params[:time_window_id].to_i
      if apt.time_window_ids && apt.time_window_ids.include?(time_window_id)
        apt.time_window_id = time_window_id
        apt.time_window_ids = nil
        apt.update(params.permit(:car_address, :car_city, :car_zipcode, :car_state))
        if apt.save
          apt.send_schedule_confirmation
          flash[:success] = "Appointment time scheduled!"
          TimeWindow.where(id: time_window_id).update_all(status: TimeWindow.statuses[:reserved])
        else
          flash[:danger] = "Scheduling appointment time failed!"
        end
      end
      redirect_to scheduleAppointments_expert_path
    end
  end

  def upload_car_images
    @car = Car.find(params[:id])
    @car_pictures = find_or_create_car_pictures(@car)
  end

  private
    def expert_update_params
      params.require(:expert).permit(:name, :email, :phone, :avatar)
    end

    def check_same_expert
      if current_expert.id != params[:id].to_i
        redirect_to '/experts'
      end
    end

    def generateTimeWindows
      time_range = Date.today...(Date.today+1.week)
      @time_windows = TimeWindow.where(date: time_range).order(:hour, :date)
                          .where(expert_id:@expert.id)
    end
end

app/helpers/experts_helper.rb
module ExpertsHelper
end

app/views/experts/_appointments.html.erb
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 toppad" >
  <div class="panel panel-info">
    <div class="panel-heading">
      <%= content_tag "h4", @appointment_type_str %>
    </div>
    <div class="panel-body">
      <% unless @appointments.empty? %>
      <table class="table">
        <tr>
          <th>Date</th>
          <th>Time</th>
          <th>Appointment Type</th>
          <th>Address</th>
          <th>User</th>
          <th>Car</th>
          <th>Change/Cancel</th>
        </tr>
        <% @appointments.each do |apt| %>
        <%= content_tag "tr", class: "checkbox-content",
        data: {status: appointment_type_str(apt)} do %>
        <td><%= "#{apt.time_window.date}, #{apt.time_window.date.strftime("%A")}" %></td>
        <% if apt.appointment_type == 0 %>
        <td><a href="<%= sell_request_path(apt.sell_request) %>"><%= "#{apt.time_window.hour}:00".to_time.strftime("%l %P") %></a></td>
        <% else %>
        <td><a href="<%= appointment_path(apt) %>"><%= "#{apt.time_window.hour}:00".to_time.strftime("%l %P") %></a></td>
        <% end %>
        <td><%= apt.apt_type %></td>
        <td><%= "#{apt.address}, #{apt.city}, #{apt.state}, #{apt.zipcode}" %></td>
        <td><%= link_to apt.user.name, apt.user %></td>
        <td><%= link_to "Car detail", car_path(apt.car) %></td>
        <td>
          <a data-toggle="modal" href="#change-cancel-modal">Change/Cancel</a>
        </td>
        <% end %>
        <% end %>
      </table>
      <% end %>
      <%= will_paginate @appointments %>
    </div>
  </div>
  <div id="change-cancel-modal" class="modal fade in">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <a class="btn btn-default" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span></a>
          <h4 class="modal-title">Sorry, it is not supported yet</h4>
        </div>
        <div class="modal-body">
          <p>Please contact our administrator at 000-000-000</p>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dalog -->
  </div><!-- /.modal -->
</div>

app/views/experts/_expert_profile.html.erb
 <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 toppad" >
  <div class="panel panel-info">
    <div class="panel-heading">
      <%= content_tag "h3", current_expert.name, class: "panel-title" %>
    </div>
    <div class="panel-body">
      <%= form_for(@expert) do |f| %>
      <div class="row same-height-table">
        <div class="col-md-4 col-lg-4 picture-container same-height-col" align="center">
          <% avatar = @expert.avatar? ? @expert.avatar.url : "default_avatar.png" %>
          <div class="thumbnail">
            <%= image_tag avatar, class: "img-responsive picture-preview" %>
            <div class="caption">
              <p>
                <a type="button" class="picture-upload-btn btn btn-sm btn-primary">Change Avatar</a>
              </p>
            </div>
          </div>
          <%= f.file_field :avatar, class: "picture-file-field" %>
        </div>
        <div class=" col-md-8 col-lg-8 same-height-col info-form-container">
          <table class="table table-user-information">
            <tbody>
              <tr>
                <td>Name:</td>
                <td><%= f.text_field :name, class: "form-control" %></td>
              </tr>
              <tr>
                <td>Email address:</td>
                <td><%= f.text_field :email, class: "form-control" %></td>
              </tr>
              <tr>
                <td>Phone Number</td>
                <td><%= f.text_field :phone, class: "form-control" %></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
      <div class="panel-footer">
        <%= f.submit "Update", class: "btn btn-sm btn-success" %>
        <span class="pull-right">
          <a type="button" class="btn btn-sm btn-danger">Cancel</a>
        </span>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/experts/_reports.html.erb
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 toppad" >
  <div class="panel panel-info">
    <div class="panel-heading">
      <h4>Reports</h4>
    </div>
    <div class="panel-body">
      <% unless @reports.empty? %>
      <table class="table">
        <tr>
          <th>Date</th>
          <th>Time</th>
          <th>Car</th>
          <th>Report</th>
        </tr>
        <% @reports.each do |apt| %>
        <% car = apt.car %>
        <% model = car.car_model %>
        <tr>
          <td><%= "#{apt.time_window.date}, #{apt.time_window.date.strftime("%A")}" %></td>
          <td><a href="<%= sell_request_path(apt.sell_request) %>"><%= "#{apt.time_window.hour}:00".to_time.strftime("%l %P") %></a></td>
          <td><%= link_to "#{model.year} #{model.make}, #{model.model}" , car_path(apt.car) %></td>
          <td><%= link_to "edit", edit_car_path(apt.car), class: "btn btn-sm btn-primary" %></td>
        </tr>
        <% end %>
      </table>
      <% end %>
    </div>
  </div>
</div>

app/views/experts/appointments.js.erb
$('#appointments').addClass('active in');
$('#appointments').html("<%= j (render partial: 'appointments') %>");
$('#appointments').siblings('.tab-pane').removeClass('active in');
$('#appointments').tab('show');

app/views/experts/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xs-offset-0 col-sm-offset-0 col-md-offset-3 col-lg-offset-3 toppad" >

      <div class="panel panel-info">
        <div class="panel-heading">
          <%= content_tag "h3", current_expert.name, class: "panel-title" %>
        </div>
        <div class="panel-body">
          <%= form_for(@expert) do |f| %>
            <div class="row">
              <div class="col-md-3 col-lg-3 " align="center">
                <img alt="User Pic" src="http://babyinfoforyou.com/wp-content/uploads/2014/10/avatar-300x300.png"
                     class="img-circle img-responsive">
              </div>
              <div class=" col-md-9 col-lg-9 ">
                <table class="table table-user-information">
                  <tbody>
                  <tr>
                    <td>User Name:</td>
                    <td><%= f.text_field :name, class: "form-control" %></td>
                  </tr>
                  <tr>
                    <td>Email address:</td>
                    <td><%= f.text_field :email, class: "form-control" %></td>
                  </tr>
                  <tr>
                    <td>Phone Number</td>
                    <td><%= f.text_field :phone, class: "form-control" %></td>
                  </tr>
                  </tbody>
                </table>
              </div>
            </div>
            <div class="panel-footer">
              <%= f.submit "Update", class: "btn btn-sm btn-success" %>
              <span class="pull-right">
                <a type="button" class="btn btn-sm btn-danger">Cancel</a>
              </span>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/experts/editAvailableTime.html.erb
<%= provide(:title, 'Edit Your Available Times') %>

<div class="container">
  <hr class="tall">
  <div class="row">
    <div class="col-md-12">
      <h2 class="mb-none"><strong>Edit Your Available Times</strong></h2>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">

      <%= form_tag('updateAvailableTime', method: :post) do |f|%>

        <div class="panel-heading">
          <h4 class="panel-title">
            Available Time Windows:
          </h4>
        </div>
        <div class="row">
          <div class="form-group">
            <div class="col-md-12">
              <%= render 'shared/time_window' %>
            </div>
          </div>
        </div>

        <div id="time_window_ids">
          <% time_windows = TimeWindow.where(expert_id: @expert.id).where.not(status:0).where(date: Date.today..(Date.today+1.week)) %>
          <% if time_windows.size != 0 %>
              <% time_windows.each do |tw| %>
                  <%= hidden_field_tag "time_window_ids[]", tw.id %>
              <% end %>
          <% else %>
              <%= hidden_field_tag "time_window_ids[]", :multiple => true %>
          <% end %>
        </div>

        <div class="row">
          <div class="form-group">
            <div class="col-md-12">
              <%= submit_tag "Submit", class: "btn btn-primary pull-right mb-xl" %>
            <% end %>
            </div>
          </div>
        </div>

    </div>
  </div>
</div>

<%= render 'shared/time_window_script_expert' %>

app/views/experts/reports.js.erb
$('#appointments').addClass('active in');
$('#appointments').html("<%= j (render partial: 'reports') %>");
$('#appointments').siblings('.tab-pane').removeClass('active in');
$('#appointments').tab('show');

app/views/experts/show.html.erb
<div class="container">
  <div class="row profile">
    <div class="col-md-3">
      <div class="profile-sidebar">
        <!-- SIDEBAR USERPIC -->
        <div class="profile-userpic">
          <% avatar = @expert.avatar? ? @expert.avatar.url : "default_avatar.png" %>
          <%= image_tag avatar, class: "img-responsive", alt: "" %>
        </div>
        <div class="profile-usertitle">
          <div class="profile-usertitle-name">
            <%= @expert.name %>
          </div>
          <div class="profile-usertitle-job">
            Auto Genius
          </div>
        </div>
        <!-- END SIDEBAR BUTTONS -->
        <!-- SIDEBAR MENU -->
        <div class="profile-usermenu">
          <ul class="nav nav-tabs nav-stacked">
            <li class="active">
              <a href="#profile" data-toggle="tab">
                <i class="glyphicon glyphicon-user"></i>
                Profile</a>
            </li>
            <li>
              <a href="#appointment-types" data-toggle="collapse">
                <i class="glyphicon glyphicon-calendar"></i>
                Appointments </a>
            </li>
            <ul class="subnav nav nav-tabs nav-stacked collapse" id="appointment-types">
              <li>
                <%= link_to "Inspection", appointments_expert_path(current_expert, type: Appointment::TYPE_SELL),
                            data: { toggle: "tab", toggle_dest: "appointments" }, class: "subnavtab", remote: true %>
              </li>
              <li>
                <%= link_to "Test Drive", appointments_expert_path(current_expert, type: Appointment::TYPE_TEST_DRIVE),
                            data: { toggle: "tab", toggle_dest: "appointments" }, class: "subnavtab", remote: true %>
              </li>
              <li>
                <%= link_to "Delivery", appointments_expert_path(current_expert, type: Appointment::TYPE_DELIVERY),
                            data: { toggle: "tab", toggle_dest: "appointments" }, class: "subnavtab", remote: true %>
              </li>
            </ul>
            <li>
              <a href="#reports" data-toggle="collapse">
                <i class="fa fa-folder"></i>
                Reports </a>
            </li>
            <ul class="subnav nav nav-tabs nav-stacked collapse" id="reports">
              <li>
                <%= link_to "New Reports", reports_expert_path(current_expert, type: Car::STATUS_PRE_INSPECTED_KEY),
                            data: { toggle: "tab", toggle_dest: "reports" }, class: "subnavtab", remote: true %>
              </li>
              <li>
                <%= link_to "Change Reports", reports_expert_path(current_expert, type: Car::STATUS_INSPECTED_KEY),
                            data: { toggle: "tab", toggle_dest: "reports" }, class: "subnavtab", remote: true %>
              </li>
            </ul>
            <li>
              <li>
                <%= link_to editAvailableTime_expert_path(current_expert) do %>
                  <i class="fa fa-clock-o"></i> Schedule Work Time
                <% end %>
              </li>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="col-md-9">
      <div class="tab-content">
        <div class="tab-pane fade active in" id="profile">
          <%= render partial: "expert_profile" %>
        </div>
        <div class="tab-pane fade" id="appointments">
        </div>
    </div>
  </div>
</div>

app/views/experts/show_appointments.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <hr class="tall">
    </div>

    <div class="row checkbox-container">
      <span class="button-checkbox">
        <button id="test-drive" type="button" class="btn" data-color="primary">Test Drive</button>
          <input type="checkbox" class="hidden" />
      </span>
      <span class="button-checkbox">
        <button id="sell" type="button" class="btn" data-color="primary">Sell</button>
          <input type="checkbox" class="hidden" />
      </span>
    </div>

    <% unless @appointments.empty? %>
      <div class="col-md-12">
        <h4>Appointments</h4>
      </div>
      <table class="table">
        <tr>
          <th>Date</th>
          <th>Time</th>
          <th>Appointment Type</th>
          <th>Address</th>
          <th>User</th>
          <th>Car</th>
          <th>Change/Cancel</th>
        </tr>
        <% @appointments.each do |apt| %>
          <%= content_tag "tr",
                          class: "checkbox-content",
                          data: {status: appointment_type_str(apt)} do %>
                <% datetime_str = apt.time_window ? "#{apt.time_window.date}, #{apt.time_window.date.strftime("%A")}" : "Undetermined" %>
                <% time_str = apt.time_window ? "#{apt.time_window.hour}:00".to_time.strftime("%l %P") : "Undetermined" %>
                   <td><%= "#{datetime_str}" %></td>
            <% if apt.appointment_type == 0 %>
              <td><a href="<%= sell_request_path(apt.sell_request) %>"><%= time_str %></a></td>
            <% else %>
              <td><a href="<%= appointment_path(apt) %>"><%= time_str %></a></td>
            <% end %>
            <td><%= apt.apt_type %></td>
            <td><%= "#{apt.address}, #{apt.city}, #{apt.state}, #{apt.zipcode}" %></td>
            <td><%= link_to apt.user.name, apt.user %></td>
            <td><%= link_to "Car detail", car_path(apt.car) if apt.car %></td>
            <td>
              <%= link_to "Change", edit_appointment_path(apt) %> /
              <%= link_to "Cancel", appointment_path(apt), method: :delete %>
            </td>
          <% end %>
        <% end %>
      </table>
    <% end %>
  </div>
</div>

app/views/experts/show_reports.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <hr class="tall">
    </div>

    <% unless @unfinished_reports.empty? %>
      <div class="col-md-12">
        <h4>Unfinished Reports</h4>
      </div>
      <%= render partial: "shared/report", locals: { reports: @unfinished_reports } %>
    <% end %>
  </div>

  <% unless @finished_reports.empty? %>
    <div class="col-md-12">
      <h4>Finished Reports</h4>
    </div>
    <%= render partial: "shared/report", locals: { reports: @finished_reports } %>
  <% end %>
</div>
</div>